### ISSUE TITLE
Script that privileges org and space no longer fails silently

### ISSUE THREAD

**Issue by jtuttle** [conjurdemos/cloudfoundry-conjur-demo#40]
If the [pcf-with-installed-tile/bin/4-privilege-org-space](https://github.com/conjurdemos/cloudfoundry-conjur-demo/blob/master/pcf-with-installed-tile/bin/4-privilege-org-space) script fails during policy load, it will fail silently. The demo will continue to completion and the demo app will be unable to retrieve secrets because the org and space layers have never been privileged to read secrets. The errors are masked by the `-d` flag on the `docker run` command. We may just be able to remove it.

**Comment by micahlee** [comment]
Fixed by #41, specifically cd791822f259165d0012a7628938e5b9e20bfb68
