### ISSUE TITLE
Installed Tile Demo should be easier to use

### ISSUE THREAD

**Issue by micahlee** [conjurdemos/cloudfoundry-conjur-demo#45]
The Installed Tile Demo currently assumes that the user operating the demo is a CyberArk developer.

The documentation and scripts should be refactored to remove this assumption and make it easier for anyone who has admin access to a CloudFoundry foundation to use these scripts to deploy a demo application with Conjur.

Exhibit A) Notes from a user who did eventually get the demo working:

> The README says that the conjur service tile should be installed before which is great *BUT* all the tile configurations needs to be fulfilled according to the policy settings such as the cf-service-broker host api and the policy branch which aren’t written in the README.
>
> On script 2 when we load the policy.yaml with the cf-service-broker host we need to output the cf-service-broker api to the screen in order to grab it for the tile configuration, after that we need to pause because the person will need to manually enter all the required tile settings on the Ops Manager and then apply the changes to PCF which takes a couple of minutes.
>
> Just after the changes committed successfully we can proceed with the 3rd script which creates the conjur service instance that behind the scenes creates the according layers.
I came to all of this process because on my first runs I got the following error: `"error":{"code":"not_found","message":"Layer 'cf/e0a41565-bb31-4fbd-a073-77afb4b099de' not found in account 'pcf'","target":"layer","details":{"code":"not_found","target":"id","message":"pcf:layer:cf/e0a41565-bb31-4fbd-a073-77afb4b099de"}}}`

**Comment by izgeri** [comment]
Resolved in #60
